### ISSUE TITLE
Add / Delete node at position x

### ISSUE THREAD

**Issue by Kevin-Dorscher** [CS383Team2/Goofy_Lights_Editor#8]
I was wondering how you guys wanted to do the indexing scheme for this...

What I had in mind:
1. create a global counter for the total number of nodes in the linked list.
2. index either from 0 to (n -1) or 1 to (n)
a) Indexing at 0 makes the head node 0, and the tail (n - 1)
b) Indexing at 1 makes the head node 1, and the tail (n).

3. Traverse the list until a local counter == position passed in
4. delete / add node at that position and adjust pointers accordingly.

Note:
my plan was / is to traverse from the head every time as I don't think 
the traversal will ever take so much time that there would be any noticable
lag time, even with 1,000 nodes or more the traversal time is still going to be almost nothing.
That being said, if later on in the development process we reach a point where
traversing the whole list takes too much time I can alter these functions accordingly.

**Comment by Kevin-Dorscher** [comment]
Thats actually super cool that you can add those labels....

**Comment by Cyberzoid1** [comment]
The FrameList already has a count of total nodes here:
https://github.com/CS383Team2/Goofy_Lights_Editor/blob/f501a04cc11781b437ed473b1d6d0a5a61cfd7e3/GoofyLightsEditor/FrameList.h#L24

I would vote that you save your last search pointer and start at that pointer when linearly looking through the list. Chances are that you are searching for something right next to it.
`Node srchPtr`  // address of last search
`int srchPos` // index of last search
Flow
>create list  set srchPtr to head
> search for position x
> start at srchPtr and traverse to x
> save srchPtr & srchPos = x

Now next time you search you will likely be closer to your goal if you start at srchPtr instead of head
> compare direction is x > srchPos OR x < srchPos
> since the FrameList is doubly linked you can go backwords or forwards

I'm guessing most of the time the user is searching for x+1 or x-1 from your last search. Humans work linearly not randomly.

**Comment by Kevin-Dorscher** [comment]
That was plan for it the traversal takes too long, but I'm not sure if it is actually needed or not. For example if we had say 1000 nodes and the overall traversal time is < 1 sec, then we may not really need to return a pointer at all. I'm going to run some tests and see how long the traversal takes for a large size of n. I may set it up the way described above anyway, I was just looking for input from everyone, thanks Nick.

**Comment by Kevin-Dorscher** [comment]
Update: After testing

So, I wrote a small program to add 1000 nodes to a linked list storing 3 int values for each node. I started with the head of the list traversed the whole list adding the new node to the tail each time. After the list contained 1000 nodes I printed out the entire list, starting from the head and set up some timers. Not only was the time 0 (in seconds) for traversing the list, but the entire program (add 1000 nodes to the tail of a linked list, traversing from the head, and printing the entire linked list traversing from the head) took less then 1 second overall. Though this is an approx. estimation as my timers returned 0 and it completed so fast all i can do is guess.
